name: build-release
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "tools/python_requirements.txt"

      - name: actual building
        run: antistasi-sqf-tools docs build -b release

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src
          git commit -m "building docs-folder"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIDDIUS_TOKEN }}
